# Reamp prefix to be more comfortable (remember to also remap system caps lock to control)
set-option -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Ensure the windows are 1-indexed
set-option -g base-index 1
set-option -g pane-base-index 1

# Re-number windows normally
bind _ move-window -r

setw -g mode-keys vi
setw -g mouse on

# Increase scroll-back buffer
setw -g history-limit 100000

# Override tmux terminal title set
set-option -g set-titles-string "#{pane_title}"

# Setup 'v' to begin selection as in Vim
# New syntax for 2.4 tmux version:
bind-key -T copy-mode-vi 'v' send -X begin-selection
# NOTE: Settings required for Mac, requires 'reattach-to-user-namespace' to be installed via brew
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Start new windows in path of current pane
bind c new-window -c "#{pane_current_path}"

# Easier split key bindings (also start panes in path of current pane)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# vim-like pane switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Unbind pane switching keys
unbind Up
unbind Down
unbind Left
unbind Right

# Add key bindings for window swapping
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# Enable true colours for vim
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Lower escape time
set-option -sg escape-time 0

# Set such that autoread works in Neovim
set-option -s focus-events on
set-option -s extended-keys on

