# Reamp prefix to be more comfortable (remember to also remap system caps lock to control)
set-option -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Ensure the windows are 1-indexed
set-option -g base-index 1
set-option -g pane-base-index 1

# Re-number windows normally
bind _ move-window -r

setw -g mode-keys vi
setw -g mouse on

# Increase scroll-back buffer
setw -g history-limit 100000

# Override tmux terminal title set
set-option -g set-titles-string "#{pane_title}"

# Setup 'v' to begin selection as in Vim
# New syntax for 2.4 tmux version:
bind-key -T copy-mode-vi 'v' send -X begin-selection
# NOTE: Settings required for Mac, requires 'reattach-to-user-namespace' to be installed via brew
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Start new windows in path of current pane
bind c new-window -c "#{pane_current_path}"

# Key binding to open a session in the same directory as current pane
bind-key S command-prompt -p "Session name:" "new-session -c '#{pane_current_path}' -s '%%'"

# Easier split key bindings (also start panes in path of current pane)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# vim-like pane switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Unbind pane switching keys
unbind Up
unbind Down
unbind Left
unbind Right

# Add key bindings for window swapping
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# Enable true colours for vim
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Lower escape time
set-option -sg escape-time 0

# Set such that autoread works in Neovim
set-option -s focus-events on
set-option -s extended-keys on

# Customize what tmux uses for automatic naming
set-option -g automatic-rename-format '#{b:pane_current_command}'


##
# Styling
##

# Move status bar to the top
# set-option -g status-postition top

# Colours
RED="#e44172"
GREEN="#b2e052"
YELLOW="#ee9b40"
BLUE="#a782f7"
MAGENTA="#e44172"
CYAN="#84d6eb"
BLACK="#212121"

DARK_GRAY="#32302F"
LIGHT_GRAY="#4F4946"
BG="#212121"
FG="#cecec3"

# Nerdfont Chars
HALF_ROUND_OPEN="#(printf '\uE0B6')"
HALF_ROUND_CLOSE="#(printf '\uE0B4')"
TRIANGLE_OPEN="#(printf '\uE0B2')"
TRIANGLE_CLOSE="#(printf '\uE0B0')"

set-option -g status-style bg=default,fg=${FG}

set-option -g status-justify centre
# set-option -g status-justify absolute-centre

set-option -g status-left "\
#[bg=default,fg=${LIGHT_GRAY}]${HALF_ROUND_OPEN}\
#[bg=${LIGHT_GRAY},fg=${YELLOW}]#S \
#[bg=default,fg=${LIGHT_GRAY}]${TRIANGLE_CLOSE}\
"
set-option -g status-right "\
#[bg=default,fg=${LIGHT_GRAY}]${TRIANGLE_OPEN}\
#[bg=${LIGHT_GRAY},fg=${CYAN}] #h\
#[bg=default,fg=${LIGHT_GRAY}]${HALF_ROUND_CLOSE}\
"

set-option -g status-left-length 100
set-option -g status-right-length 100

# This is to display the first 3 characters of the current directory
# NOTE: #{s|/.*/||:pane_current_path} to get last segment of current pane path
# #{=|3|…|;s|/.*/||:pane_current_path} to get 1st 3 chars of last segment of current pane path
# #{=|3|…|;b:pane_current_path} is much simpler though
# #W for normal window name
# set-option -g window-status-format "\
#  \
# #I\
# :\
# #{=|3|…|;b:pane_current_path}\
#  \
# "

set-option -g window-status-format "\
 \
#I\
:\
#W\
 \
"

set-option -g window-status-current-format "\
#[fg=${LIGHT_GRAY},bg=default]${HALF_ROUND_OPEN}\
#[fg=${GREEN},bg=${LIGHT_GRAY}]#I\
#[fg=${GREEN}]:\
#[fg=${GREEN}]#W\
#[fg=${LIGHT_GRAY},bg=default]${HALF_ROUND_CLOSE}\
"

set-option -g window-status-separator ""
